import React, {useEffect, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {BookOpen, Scale, Search, ShieldCheck, ExternalLink, Clock3, GitCompareArrows, AlertTriangle, Database, CheckCircle2} from 'lucide-react';
import './styles.css';

const API = import.meta.env.VITE_API_URL || 'http://127.0.0.1:8000';
type Citation={document_number:string;title:string;article:string;clause?:string;quote:string;source_url?:string;score:number};
type Result={run_id:string;answer:string;citations:Citation[];confidence:number;warnings:string[];pipeline_version:string;latency_ms:number;retrieved_provisions:any[]};
const examples=['Làm thêm vào ngày nghỉ hằng tuần được trả tối thiểu bao nhiêu?', 'Thử việc tối đa bao lâu với vị trí kỹ thuật trình độ cao đẳng?', 'Năm 2026 cần đóng BHXH bao nhiêu năm để hưởng lương hưu?', 'Mức giảm trừ gia cảnh hiện được quy định thế nào?'];

function App(){
 const [token,setToken]=useState(''); const [question,setQuestion]=useState(examples[0]); const [domain,setDomain]=useState('labor'); const [date,setDate]=useState('2026-01-01'); const [level,setLevel]=useState('L4'); const [result,setResult]=useState<Result|null>(null); const [compare,setCompare]=useState<Record<string,Result>|null>(null); const [loading,setLoading]=useState(false); const [error,setError]=useState('');
 useEffect(()=>{fetch(`${API}/api/v1/auth/login`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:'demo@legalrag.vn',password:'demo1234'})}).then(r=>r.json()).then(x=>setToken(x.access_token)).catch(()=>setError('Không kết nối được API.'));},[]);
 async function run(comparing=false){setLoading(true);setError('');setResult(null);setCompare(null);try{const path=comparing?'query/compare':'query';const body=comparing?{question,applicable_date:date,domain,pipelines:['L1','L4','L7']}:{question,applicable_date:date,domain,pipeline_level:level};const r=await fetch(`${API}/api/v1/${path}`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify(body)});if(!r.ok)throw new Error(await r.text());const data=await r.json();comparing?setCompare(data):setResult(data);}catch(e){setError(e instanceof Error?e.message:'Có lỗi xảy ra');}finally{setLoading(false)}}
 return <div className="app">
  <header><div className="brand"><div className="logo"><Scale size={22}/></div><div><strong>Vietnam Legal RAG</strong><span>Tra cứu pháp luật có căn cứ</span></div></div><div className="status"><span></span> Knowledge base online</div></header>
  <main><aside><p className="eyebrow">PHẠM VI TRA CỨU</p>{[['labor','Luật Lao động'],['social_insurance','Bảo hiểm xã hội'],['personal_income_tax','Thuế thu nhập cá nhân']].map(([v,l])=><button className={domain===v?'nav active':'nav'} onClick={()=>setDomain(v)} key={v}><BookOpen size={17}/>{l}</button>)}<div className="asideCard"><ShieldCheck/><strong>Tra cứu an toàn</strong><p>Câu trả lời chỉ được tạo từ nguồn đã kiểm chứng. Đây không phải tư vấn pháp lý.</p></div><div className="corpus"><Database size={16}/><span><b>5</b> văn bản demo<br/><b>12</b> điều khoản</span></div></aside>
  <section className="workspace"><div className="intro"><p className="eyebrow">LEGAL INTELLIGENCE</p><h1>Hỏi luật. Nhận câu trả lời<br/><em>có thể kiểm chứng.</em></h1><p>Tra cứu theo đúng thời điểm hiệu lực, xem điều khoản nguồn và so sánh các pipeline retrieval.</p></div>
   <div className="querybox"><textarea value={question} onChange={e=>setQuestion(e.target.value)} placeholder="Nhập câu hỏi pháp lý…"/><div className="controls"><label>Lĩnh vực<select value={domain} onChange={e=>setDomain(e.target.value)}><option value="labor">Lao động</option><option value="social_insurance">BHXH</option><option value="personal_income_tax">Thuế TNCN</option></select></label><label>Ngày áp dụng<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>Pipeline<select value={level} onChange={e=>setLevel(e.target.value)}>{['L0','L1','L2','L3','L4','L7'].map(x=><option key={x}>{x}</option>)}</select></label><button className="primary" disabled={!token||loading} onClick={()=>run(false)}><Search size={18}/>{loading?'Đang tra cứu…':'Tra cứu'}</button><button className="secondary" disabled={!token||loading} onClick={()=>run(true)}><GitCompareArrows size={18}/>So sánh</button></div></div>
   <div className="examples"><span>Thử nhanh:</span>{examples.map(x=><button key={x} onClick={()=>setQuestion(x)}>{x}</button>)}</div>
   {error&&<div className="warning"><AlertTriangle/> {error}</div>}
   {result&&<ResultCard title={`Kết quả ${level}`} data={result}/>} 
   {compare&&<div className="compare">{Object.entries(compare).map(([k,v])=><ResultCard key={k} title={k} data={v}/>)}</div>}
  </section></main></div>
}
function ResultCard({title,data}:{title:string,data:Result}){return <article className="result"><div className="resultHead"><div><span className="pill">{title}</span><b>{Math.round(data.confidence*100)}% tin cậy</b></div><span><Clock3 size={15}/>{data.latency_ms} ms</span></div>{data.warnings.map(w=><div className="warning" key={w}><AlertTriangle size={17}/>{w}</div>)}<div className="answer"><div className="answerTitle"><CheckCircle2 size={19}/>Câu trả lời dựa trên nguồn</div>{data.answer.split('\n').map((x,i)=><p key={i}>{x}</p>)}</div>{data.citations.length>0&&<div className="sources"><h3>Nguồn viện dẫn <span>{data.citations.length}</span></h3>{data.citations.map((c,i)=><div className="source" key={i}><div className="sourceTop"><div><span className="num">{i+1}</span><strong>{c.document_number}</strong> · Điều {c.article}{c.clause&&`, khoản ${c.clause}`}</div>{c.source_url&&<a href={c.source_url} target="_blank">Mở văn bản <ExternalLink size={14}/></a>}</div><p>“{c.quote}”</p><small>{c.title} · relevance {c.score.toFixed(3)}</small></div>)}</div>}<footer>Pipeline {data.pipeline_version} · {data.retrieved_provisions.length} chunks retrieved · Chi phí $0.0000</footer></article>}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
